// Unity Build generated by CMake
#include </home/ubuntu/lemon-all/duckdb_fixed_version/duckdb_0_8_1_remon_atached/src/core_functions/scalar/random/random.cpp>
#include </home/ubuntu/lemon-all/duckdb_fixed_version/duckdb_0_8_1_remon_atached/src/core_functions/scalar/random/setseed.cpp>
