// Unity Build generated by CMake
#include </home/ubuntu/lemon-all/duckdb_fixed_version/duckdb_0_8_1_remon_atached/src/core_functions/scalar/date/age.cpp>
#include </home/ubuntu/lemon-all/duckdb_fixed_version/duckdb_0_8_1_remon_atached/src/core_functions/scalar/date/current.cpp>
#include </home/ubuntu/lemon-all/duckdb_fixed_version/duckdb_0_8_1_remon_atached/src/core_functions/scalar/date/epoch.cpp>
#include </home/ubuntu/lemon-all/duckdb_fixed_version/duckdb_0_8_1_remon_atached/src/core_functions/scalar/date/date_diff.cpp>
#include </home/ubuntu/lemon-all/duckdb_fixed_version/duckdb_0_8_1_remon_atached/src/core_functions/scalar/date/date_part.cpp>
#include </home/ubuntu/lemon-all/duckdb_fixed_version/duckdb_0_8_1_remon_atached/src/core_functions/scalar/date/date_sub.cpp>
#include </home/ubuntu/lemon-all/duckdb_fixed_version/duckdb_0_8_1_remon_atached/src/core_functions/scalar/date/date_trunc.cpp>
#include </home/ubuntu/lemon-all/duckdb_fixed_version/duckdb_0_8_1_remon_atached/src/core_functions/scalar/date/make_date.cpp>
#include </home/ubuntu/lemon-all/duckdb_fixed_version/duckdb_0_8_1_remon_atached/src/core_functions/scalar/date/strftime.cpp>
#include </home/ubuntu/lemon-all/duckdb_fixed_version/duckdb_0_8_1_remon_atached/src/core_functions/scalar/date/time_bucket.cpp>
#include </home/ubuntu/lemon-all/duckdb_fixed_version/duckdb_0_8_1_remon_atached/src/core_functions/scalar/date/to_interval.cpp>
