// Unity Build generated by CMake
#include </home/ubuntu/lemon-all/duckdb_fixed_version/duckdb_0_8_1_remon_atached/src/common/serializer/binary_serializer.cpp>
#include </home/ubuntu/lemon-all/duckdb_fixed_version/duckdb_0_8_1_remon_atached/src/common/serializer/binary_deserializer.cpp>
#include </home/ubuntu/lemon-all/duckdb_fixed_version/duckdb_0_8_1_remon_atached/src/common/serializer/buffered_deserializer.cpp>
#include </home/ubuntu/lemon-all/duckdb_fixed_version/duckdb_0_8_1_remon_atached/src/common/serializer/buffered_file_reader.cpp>
#include </home/ubuntu/lemon-all/duckdb_fixed_version/duckdb_0_8_1_remon_atached/src/common/serializer/buffered_file_writer.cpp>
#include </home/ubuntu/lemon-all/duckdb_fixed_version/duckdb_0_8_1_remon_atached/src/common/serializer/buffered_serializer.cpp>
