// Unity Build generated by CMake
#include </home/ubuntu/lemon-all/duckdb_fixed_version/duckdb_0_8_1_remon_atached/src/optimizer/rule/arithmetic_simplification.cpp>
#include </home/ubuntu/lemon-all/duckdb_fixed_version/duckdb_0_8_1_remon_atached/src/optimizer/rule/case_simplification.cpp>
#include </home/ubuntu/lemon-all/duckdb_fixed_version/duckdb_0_8_1_remon_atached/src/optimizer/rule/comparison_simplification.cpp>
#include </home/ubuntu/lemon-all/duckdb_fixed_version/duckdb_0_8_1_remon_atached/src/optimizer/rule/conjunction_simplification.cpp>
#include </home/ubuntu/lemon-all/duckdb_fixed_version/duckdb_0_8_1_remon_atached/src/optimizer/rule/constant_folding.cpp>
#include </home/ubuntu/lemon-all/duckdb_fixed_version/duckdb_0_8_1_remon_atached/src/optimizer/rule/date_part_simplification.cpp>
#include </home/ubuntu/lemon-all/duckdb_fixed_version/duckdb_0_8_1_remon_atached/src/optimizer/rule/distributivity.cpp>
#include </home/ubuntu/lemon-all/duckdb_fixed_version/duckdb_0_8_1_remon_atached/src/optimizer/rule/empty_needle_removal.cpp>
#include </home/ubuntu/lemon-all/duckdb_fixed_version/duckdb_0_8_1_remon_atached/src/optimizer/rule/enum_comparison.cpp>
#include </home/ubuntu/lemon-all/duckdb_fixed_version/duckdb_0_8_1_remon_atached/src/optimizer/rule/equal_or_null_simplification.cpp>
#include </home/ubuntu/lemon-all/duckdb_fixed_version/duckdb_0_8_1_remon_atached/src/optimizer/rule/move_constants.cpp>
#include </home/ubuntu/lemon-all/duckdb_fixed_version/duckdb_0_8_1_remon_atached/src/optimizer/rule/like_optimizations.cpp>
#include </home/ubuntu/lemon-all/duckdb_fixed_version/duckdb_0_8_1_remon_atached/src/optimizer/rule/in_clause_simplification_rule.cpp>
#include </home/ubuntu/lemon-all/duckdb_fixed_version/duckdb_0_8_1_remon_atached/src/optimizer/rule/ordered_aggregate_optimizer.cpp>
#include </home/ubuntu/lemon-all/duckdb_fixed_version/duckdb_0_8_1_remon_atached/src/optimizer/rule/regex_optimizations.cpp>
