apiVersion: apps/v1
kind: Deployment
metadata:
  name: page
spec:
  replicas: 2
  selector:
    matchLabels:
      app: page-server
  template:
    metadata:
      labels:
        app: page-server
    spec:
      imagePullSecrets:
        - name: regcred
      initContainers:
        - name: init-container
          image: busybox
          command: 
           - 'sh'
           - '-c'
           - 'sleep 6000'
              #   - "sed -i 's/MAX_RAM_IN_GB: .*/MAX_RAM_IN_GB: new_value/' /home/page_server/build-release/remon.config"
          
      containers:
        - name: page-server
          image: gabeee123/lem:pagem
          volumeMounts:
            - name: page-storage
              mountPath: /mnt/
      volumes:
        - name: page-storage
          persistentVolumeClaim:
            claimName: page-pvc

